name: CI
on:
  push: { branches: [ main, develop ] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optional: speed up installs
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - run: npm ci
      - run: npx playwright install --with-deps chromium

      - name: Run lint + tests
        run: npm run ci

      # Optional: upload Playwright HTML report if something fails
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
